add resistor in the materials section
burabure/dactyl-keyboard pull request #1
Opened 2020-08-15 00:45 UTC by aotarola

Required for I2C Wiring

---
_This PR was started by: [git wf pr](https://github.com/groupon/git-workflow/releases/tag/v1.1.0)_

2020-08-15 06:29 UTC, burabure requested changes

2020-08-15 06:29 UTC, burabure commented on README.md
> +- [2 4.5K Ohm Resistors](https://www.amazon.com/gp/product/B07QJB3LGN/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1)
2x 4.7K

2020-08-15 16:25 UTC, aotarola commented on README.md
> +- [2 4.5K Ohm Resistors](https://www.amazon.com/gp/product/B07QJB3LGN/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1)
😅

2020-08-24 17:09 UTC, aotarola commented
closing since this data is already included in the readme now 😄

2020-08-24 17:09 UTC, closed without merging